
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `coin1`=list(
        `type`="article", 
        `author`="Torsten Hothorn, Kurt Hornik, Mark A. van de Wiel and Achim Zeileis", 
        `year`=2006, 
        `title`="A Lego system for conditional inference", 
        `publisher`="The American Statistician", 
        `volume`="60(3)", 
        `pages`="257-263"), 
    `coin2`=list(
        `type`="article", 
        `author`="Torsten Hothorn, Kurt Hornik, Mark A. van de Wiel and Achim Zeileis", 
        `year`=2008, 
        `title`="Implementing a class of permutation tests: The coin package", 
        `publisher`="Journal of Statistical Software", 
        `volume`="28(8)", 
        `pages`="1-23"), 
    `survival1`=list(
        `type`="software", 
        `author`="Terry M Therneau", 
        `year`=2020, 
        `title`="A Package for Survival Analysis in R", 
        `publisher`="[R package]. Retrieved from https://cran.r-project.org/package=survival", 
        `url`="https://cran.r-project.org/package=survival"), 
    `survival2`=list(
        `type`="book", 
        `author`="Terry M. Therneau and Patricia M. Grambsch", 
        `year`=2000, 
        `title`="Modeling Survival Data: Extending the Cox Model", 
        `publisher`="Springer", 
        `address`="New York"))
