
# This file is automatically generated, you probably don't want to edit this

survOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "survOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            event = NULL,
            eventLevel = NULL,
            elapsed = NULL,
            groups = NULL,
            sc = TRUE,
            hf = FALSE,
            chf = FALSE,
            ci = FALSE,
            cens = TRUE, ...) {

            super$initialize(
                package='deathwatch',
                name='surv',
                requiresData=TRUE,
                ...)

            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event,
                suggested=list(
                    "nominal"))
            private$..eventLevel <- jmvcore::OptionLevel$new(
                "eventLevel",
                eventLevel,
                variable="(event)")
            private$..elapsed <- jmvcore::OptionVariable$new(
                "elapsed",
                elapsed,
                suggested=list(
                    "continuous"))
            private$..groups <- jmvcore::OptionVariable$new(
                "groups",
                groups,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "nominal",
                    "ordinal",
                    "nominaltext"))
            private$..sc <- jmvcore::OptionBool$new(
                "sc",
                sc,
                default=TRUE)
            private$..hf <- jmvcore::OptionBool$new(
                "hf",
                hf,
                default=FALSE)
            private$..chf <- jmvcore::OptionBool$new(
                "chf",
                chf,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..cens <- jmvcore::OptionBool$new(
                "cens",
                cens,
                default=TRUE)

            self$.addOption(private$..event)
            self$.addOption(private$..eventLevel)
            self$.addOption(private$..elapsed)
            self$.addOption(private$..groups)
            self$.addOption(private$..sc)
            self$.addOption(private$..hf)
            self$.addOption(private$..chf)
            self$.addOption(private$..ci)
            self$.addOption(private$..cens)
        }),
    active = list(
        event = function() private$..event$value,
        eventLevel = function() private$..eventLevel$value,
        elapsed = function() private$..elapsed$value,
        groups = function() private$..groups$value,
        sc = function() private$..sc$value,
        hf = function() private$..hf$value,
        chf = function() private$..chf$value,
        ci = function() private$..ci$value,
        cens = function() private$..cens$value),
    private = list(
        ..event = NA,
        ..eventLevel = NA,
        ..elapsed = NA,
        ..groups = NA,
        ..sc = NA,
        ..hf = NA,
        ..chf = NA,
        ..ci = NA,
        ..cens = NA)
)

survResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        tests = function() private$.items[["tests"]],
        sc = function() private$.items[["sc"]],
        hf = function() private$.items[["hf"]],
        chf = function() private$.items[["chf"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Survival Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Survival Analysis",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `visible`="(groups)"),
                    list(
                        `name`="censored", 
                        `title`="Censored", 
                        `type`="integer"),
                    list(
                        `name`="events", 
                        `title`="Events", 
                        `type`="integer"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="prop", 
                        `title`="Proportion", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="median", 
                        `title`="Median"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tests",
                title="Tests",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups"),
                columns=list(
                    list(
                        `name`="v1", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key[1])"),
                    list(
                        `name`="v2", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key[2])"),
                    list(
                        `name`="stat[1]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Log-rank"),
                    list(
                        `name`="stat[2]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Gehan"),
                    list(
                        `name`="stat[3]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Tarone-Ware"),
                    list(
                        `name`="stat[4]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Peto-Peto"),
                    list(
                        `name`="z[1]", 
                        `title`="z"),
                    list(
                        `name`="z[2]", 
                        `title`="z"),
                    list(
                        `name`="z[3]", 
                        `title`="z"),
                    list(
                        `name`="z[4]", 
                        `title`="z"),
                    list(
                        `name`="p[1]", 
                        `title`="p"),
                    list(
                        `name`="p[2]", 
                        `title`="p"),
                    list(
                        `name`="p[3]", 
                        `title`="p"),
                    list(
                        `name`="p[4]", 
                        `title`="p"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="sc",
                title="Survival Curve",
                visible="(sc)",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups",
                    "cens",
                    "ci")))
            self$add(jmvcore::Image$new(
                options=options,
                name="hf",
                title="Hazard Function",
                visible="(hf)",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups")))
            self$add(jmvcore::Image$new(
                options=options,
                name="chf",
                title="Cumulative Hazard Function",
                visible="(chf)",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups")))}))

survBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "survBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'deathwatch',
                name = 'surv',
                version = c(1,0,0),
                options = options,
                results = survResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Survival Analysis
#'
#' 
#' @param data .
#' @param event .
#' @param eventLevel .
#' @param elapsed .
#' @param groups .
#' @param sc .
#' @param hf .
#' @param chf .
#' @param ci .
#' @param cens .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tests} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$hf} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$chf} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
surv <- function(
    data,
    event,
    eventLevel,
    elapsed,
    groups,
    sc = TRUE,
    hf = FALSE,
    chf = FALSE,
    ci = FALSE,
    cens = TRUE) {

    if ( ! requireNamespace('jmvcore'))
        stop('surv requires jmvcore to be installed (restart may be required)')

    options <- survOptions$new(
        event = event,
        eventLevel = eventLevel,
        elapsed = elapsed,
        groups = groups,
        sc = sc,
        hf = hf,
        chf = chf,
        ci = ci,
        cens = cens)

    results <- survResults$new(
        options = options)

    analysis <- survClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
