
# This file is automatically generated, you probably don't want to edit this

survOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "survOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsed = NULL,
            event = NULL,
            eventLevel = NULL,
            groups = NULL,
            tests = NULL,
            sc = TRUE,
            chf = FALSE,
            ci = FALSE,
            cens = FALSE,
            risktable = FALSE,
            plotmedian = FALSE,
            logscale = FALSE,
            timeunits = "", ...) {

            super$initialize(
                package='deathwatch',
                name='surv',
                requiresData=TRUE,
                ...)

            private$..elapsed <- jmvcore::OptionVariable$new(
                "elapsed",
                elapsed,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..eventLevel <- jmvcore::OptionLevel$new(
                "eventLevel",
                eventLevel,
                variable="(event)")
            private$..groups <- jmvcore::OptionVariable$new(
                "groups",
                groups,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..tests <- jmvcore::OptionNMXList$new(
                "tests",
                tests,
                options=list(
                    "logrank",
                    "gehan",
                    "tarone-ware",
                    "peto-peto"))
            private$..sc <- jmvcore::OptionBool$new(
                "sc",
                sc,
                default=TRUE)
            private$..chf <- jmvcore::OptionBool$new(
                "chf",
                chf,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..cens <- jmvcore::OptionBool$new(
                "cens",
                cens,
                default=FALSE)
            private$..risktable <- jmvcore::OptionBool$new(
                "risktable",
                risktable,
                default=FALSE)
            private$..plotmedian <- jmvcore::OptionBool$new(
                "plotmedian",
                plotmedian,
                default=FALSE)
            private$..logscale <- jmvcore::OptionBool$new(
                "logscale",
                logscale,
                default=FALSE)
            private$..timeunits <- jmvcore::OptionString$new(
                "timeunits",
                timeunits,
                default="")

            self$.addOption(private$..elapsed)
            self$.addOption(private$..event)
            self$.addOption(private$..eventLevel)
            self$.addOption(private$..groups)
            self$.addOption(private$..tests)
            self$.addOption(private$..sc)
            self$.addOption(private$..chf)
            self$.addOption(private$..ci)
            self$.addOption(private$..cens)
            self$.addOption(private$..risktable)
            self$.addOption(private$..plotmedian)
            self$.addOption(private$..logscale)
            self$.addOption(private$..timeunits)
        }),
    active = list(
        elapsed = function() private$..elapsed$value,
        event = function() private$..event$value,
        eventLevel = function() private$..eventLevel$value,
        groups = function() private$..groups$value,
        tests = function() private$..tests$value,
        sc = function() private$..sc$value,
        chf = function() private$..chf$value,
        ci = function() private$..ci$value,
        cens = function() private$..cens$value,
        risktable = function() private$..risktable$value,
        plotmedian = function() private$..plotmedian$value,
        logscale = function() private$..logscale$value,
        timeunits = function() private$..timeunits$value),
    private = list(
        ..elapsed = NA,
        ..event = NA,
        ..eventLevel = NA,
        ..groups = NA,
        ..tests = NA,
        ..sc = NA,
        ..chf = NA,
        ..ci = NA,
        ..cens = NA,
        ..risktable = NA,
        ..plotmedian = NA,
        ..logscale = NA,
        ..timeunits = NA)
)

survResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        compsurvTable1 = function() private$.items[["compsurvTable1"]],
        compsurvTable3 = function() private$.items[["compsurvTable3"]],
        tests = function() private$.items[["tests"]],
        sc = function() private$.items[["sc"]],
        chf = function() private$.items[["chf"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Survival Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="compsurvTable1",
                title="Events Summary",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `visible`="(groups)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="obs", 
                        `title`="Observed Events (V)", 
                        `type`="integer"),
                    list(
                        `name`="exp", 
                        `title`="Expected Events (E)", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="compsurvTable3",
                title="Median Estimates",
                clearWith=list(
                    "times",
                    "status"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text", 
                        `content`="($key)", 
                        `visible`="(groups)"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="cilb", 
                        `title`="Lower", 
                        `type`="number"),
                    list(
                        `name`="ciub", 
                        `title`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tests",
                title="Tests Summaries",
                visible="(tests)",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups"),
                columns=list(
                    list(
                        `name`="stat[logrank]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Log-rank", 
                        `visible`="(tests:logrank)"),
                    list(
                        `name`="stat[gehan]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Gehan", 
                        `visible`="(tests:gehan)"),
                    list(
                        `name`="stat[tarone-ware]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Tarone-Ware", 
                        `visible`="(tests:tarone-ware)"),
                    list(
                        `name`="stat[peto-peto]", 
                        `title`="", 
                        `type`="text", 
                        `content`="Peto-Peto", 
                        `visible`="(tests:peto-peto)"),
                    list(
                        `name`="chisqr[logrank]", 
                        `title`="Chi-Squared", 
                        `type`="number", 
                        `visible`="(tests:logrank)"),
                    list(
                        `name`="chisqr[gehan]", 
                        `title`="Chi-Squared", 
                        `type`="number", 
                        `visible`="(tests:gehan)"),
                    list(
                        `name`="chisqr[tarone-ware]", 
                        `title`="Chi-Squared", 
                        `type`="number", 
                        `visible`="(tests:tarone-ware)"),
                    list(
                        `name`="chisqr[peto-peto]", 
                        `title`="Chi-Squared", 
                        `type`="number", 
                        `visible`="(tests:peto-peto)"),
                    list(
                        `name`="df[logrank]", 
                        `title`="DF", 
                        `type`="integer", 
                        `visible`="(tests:logrank)"),
                    list(
                        `name`="df[gehan]", 
                        `title`="DF", 
                        `type`="integer", 
                        `visible`="(tests:gehan)"),
                    list(
                        `name`="df[tarone-ware]", 
                        `title`="DF", 
                        `type`="integer", 
                        `visible`="(tests:tarone-ware)"),
                    list(
                        `name`="df[peto-peto]", 
                        `title`="DF", 
                        `type`="integer", 
                        `visible`="(tests:peto-peto)"),
                    list(
                        `name`="pvalue[logrank]", 
                        `title`="P-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(tests:logrank)"),
                    list(
                        `name`="pvalue[gehan]", 
                        `title`="P-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(tests:gehan)"),
                    list(
                        `name`="pvalue[tarone-ware]", 
                        `title`="P-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(tests:tarone-ware)"),
                    list(
                        `name`="pvalue[peto-peto]", 
                        `title`="P-Value", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(tests:peto-peto)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="sc",
                title="Survival Curve",
                visible="(sc)",
                width=600,
                height=600,
                renderFun=".plot",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups",
                    "cens",
                    "ci",
                    "timeunits",
                    "risktable",
                    "plotmedian")))
            self$add(jmvcore::Image$new(
                options=options,
                name="chf",
                title="Cumulative Hazard Function",
                visible="(chf)",
                width=600,
                height=400,
                renderFun=".plot",
                clearWith=list(
                    "event",
                    "eventLevel",
                    "elapsed",
                    "groups",
                    "timeunits",
                    "logscale")))}))

survBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "survBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'deathwatch',
                name = 'surv',
                version = c(1,0,0),
                options = options,
                results = survResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Survival Analysis
#'
#' 
#' @param data .
#' @param elapsed .
#' @param event .
#' @param eventLevel .
#' @param groups .
#' @param tests .
#' @param sc .
#' @param chf .
#' @param ci .
#' @param cens .
#' @param risktable .
#' @param plotmedian .
#' @param logscale .
#' @param timeunits .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$compsurvTable1} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$compsurvTable3} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tests} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sc} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$chf} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$compsurvTable1$asDF}
#'
#' \code{as.data.frame(results$compsurvTable1)}
#'
#' @export
surv <- function(
    data,
    elapsed,
    event,
    eventLevel,
    groups,
    tests,
    sc = TRUE,
    chf = FALSE,
    ci = FALSE,
    cens = FALSE,
    risktable = FALSE,
    plotmedian = FALSE,
    logscale = FALSE,
    timeunits = "") {

    if ( ! requireNamespace('jmvcore'))
        stop('surv requires jmvcore to be installed (restart may be required)')

    if ( ! missing(elapsed)) elapsed <- jmvcore::resolveQuo(jmvcore::enquo(elapsed))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if ( ! missing(groups)) groups <- jmvcore::resolveQuo(jmvcore::enquo(groups))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsed), elapsed, NULL),
            `if`( ! missing(event), event, NULL),
            `if`( ! missing(groups), groups, NULL))

    for (v in groups) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- survOptions$new(
        elapsed = elapsed,
        event = event,
        eventLevel = eventLevel,
        groups = groups,
        tests = tests,
        sc = sc,
        chf = chf,
        ci = ci,
        cens = cens,
        risktable = risktable,
        plotmedian = plotmedian,
        logscale = logscale,
        timeunits = timeunits)

    analysis <- survClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
